### ISSUE TITLE
New entities after update

### ISSUE THREAD

**Issue by MrPePperNL** [snowienator/Home-Assistant-Prijsplafond#8]
Hello,

I'm using this intergration since like it started at begiining of January.

Today I got mention of an update being available so I read the readme and changelog. Then removed the platform from my configuration.yaml, restarted HA. Then did the update from HACS and restarted HA again.
After restart went to add the integration again. It showed the config flow however no text :
![Screenshot_20230124_183551_Home Assistant](https://user-images.githubusercontent.com/37747164/214370021-9238c64a-6b0f-427e-988e-4abe739681b1.jpg)
After selecting the correct sensors the intergration adding was succesful.

But looking at my entities I now we them as new entities instead of the already created ones : 
![Screenshot_20230124_184132_Home Assistant](https://user-images.githubusercontent.com/37747164/214370671-89f06817-6174-4bc5-b44f-d10db6ad3168.jpg)

HAOS on VM
Language set to English, location set to Netherlands.

How can I get them inline again ?

**Comment by snowienator** [comment]
Hmm.. I'm having a small internal battle with how Hassio uses config flows.. Still trying to get it to work properly for this integration.. Normally the config shows like:

Where the first selection is for energy consumers, the second for energy producers (solar panels) and the third for gas consumers. Keep in mind that once you select an entity in either list, sneaky another row will be added.. So keep an eye on what you are selecting and in what list..
![image](https://user-images.githubusercontent.com/688313/214375144-4307cd4c-1174-41cd-91bb-aa10ca92bfae.png)

Sorry for this weird way.. Hope to fix this soon as I find it to be annoying also.. 😅  

In order to get your entities in 'sync'. You could remove the old onces and then rename the entity id to what is was. So prijsplafond_gas_2 to prijsplafond_gas.

**Comment by MrPePperNL** [comment]
Thanks for quick response. I'm trying basics at python but really struggling already, then when looking at the config flow py I'm lost totally.
Seems to me there must be a solution for the fields not filling in, as other integrations have it working, hope you can find it too.

As for part 2, my old entities start at 4 January and have history till today, the new entities start today. So when removing the old ones, wouldn't I loose this history ? Or will the history be added to the new entities once I rename them ?

**Comment by MrPePperNL** [comment]
As for part 2, I just took the plunge and removed the old entities, renamed the new entities and still have my history.
